config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  resources :products do
    get :who_bought, on: :member
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main">
    
      <div class="nav-container">
        <%= render partial: "shared/navbar" %>
      </div>

      <h1><%= @page_title %></h1>

    </header>

    <section class="content">

      <nav class="side_nav">

        <% if @cart %>
          <div id="cart" class="carts">
            <%= render @cart %>
          </div>
        <% end %>

        <ul style="margin-top: 1em">
          <% current_date = DateTime.now %>
          <li class="dt-side"><%= current_date.strftime("%d/%m/%Y %H:%M") %></li>
          <br>
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
        </ul>

        <% if session[:user_id] %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders', orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav>
        <% end %>

      </nav>

      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>

    </section>
  </body>
</html>